[package]
name = "travis-docker-rust-cross"
version = "0.1.0"

[dependencies]

[dependencies.network_manager]
git = "https://github.com/resin-io-modules/network_manager"
version = "0.6"

[profile.release]
lto = true
